[우] TodoList ajax 통신하기 미션 제출합니다.
woowacourse/todolist pull request #27
Opened 2020-05-31 07:20 UTC by hwookim

update(edit)에 대한 api를 제외하고 적용 완료했습니다.

통신 요청 시 일정 시간 버퍼가 있어 기본적으로 객체 배열을 통해 각 TodoItem의 상태를 관리하고, 생성 시에만 id값을 받아오지 않아 서버 값을 통해 랜더링하도록 했습니다.
잘부탁드립니다!

2020-06-18 22:16 UTC, wmakerjun requested changes
성실한 우!!!
비동기 통신 로직까지 추가해서 구현하느라 고생이 많았어요 😄 
제가 늦게 코드리뷰 해줘서 ㅠㅠ 선택미션 1단계에서 피드백 제가 드린걸 아직 반영할 시간이 없었을텐데
비슷하게 피드백할부분이 많아서 같이 참조해주면 좋을 것 같아요 :)

너무너무너무 고생 많았구요! 피드백 반영하면서 또 커뮤니케이션해요!!! 🤩

2020-06-18 22:16 UTC, wmakerjun commented on js/TodoApp.js
> +      .catch(error => alert(error));
👍

2020-06-18 22:16 UTC, wmakerjun commented on js/TodoApp.js
> +    this.loadItems()
31lin에서는 async catch를 쓰고 있는데요 동일한 컨벤션으로 가져가면 협업할 때 더 좋겠죠? :)

2020-06-18 22:16 UTC, wmakerjun commented on js/TodoApp.js
> +    if (this.filter === FILTER.COMPLETED) {
모든 if문을 돌아야 하는 이유가 없다면 if문의 연속이 아닌, if else나 switch case로 변경하는걸 추천해요 😄 그렇지 않으면 첫번째 if문에서 종료되는 조건인 경우에도 모든 if문을 돌아야 해요 😢

2020-06-18 22:16 UTC, wmakerjun commented on js/TodoApp.js
> +    if (isAll) {
모든 if문을 돌아야 하는 이유가 없다면 if문의 연속이 아닌, if else나 switch case로 변경하는걸 추천해요 😄 그렇지 않으면 첫번째 if문에서 종료되는 조건인 경우에도 모든 if문을 돌아야 해요 😢

2020-06-18 22:16 UTC, wmakerjun commented on js/TodoApp.js
> +    const isAll = target.classList.contains("all");
`all`, `active`, `completed` 같은 클래스나 상태를 한 곳에서 상수로 관리한다면, 전체 상태가 어떤게 있는지 나중에 늘어나거나 줄어들더라고 관리하기가 편할 것 같아요 :) 상수로 한 곳에서 관리한다면, 기존에 존재하던 상수를 삭제하게 된 경우에 코드상으로도 참조가 되지 않으니 바로 문제를 확인할 수 있고, 새로운 상태가 추가될 경우에는 전체 어떤 상태가 있는지 한눈에 보기 쉬울 것 같아요 :)

2020-06-18 22:16 UTC, eastjun commented on js/component/TodoCount.js
> +export const TodoCount = class {
보통은 `class TodoCount { ... } ` 이렇게 작성을 해요 ㅎㅎ

2020-06-18 22:16 UTC, eastjun commented on js/component/TodoFilter.js
> +    const isBtn = $target.tagName === "A";
`tagName`을 통한 비교도 좋지만, 서비스가 변경되면서 `a`태그의 다른 엘리먼트가 추가된다면 원치 않는 에러를 발생시킬 수도 있을 것 같아요~! `filter`와 같은 class를 추가한 후, class를 비교하는건 어떨까요?

2020-06-18 22:16 UTC, eastjun commented on js/component/TodoInput.js
> +    const isEnter = event.key === KEY_TYPE.ENTER;
다른 class에서도 재사용할 수 있게 따로 객체로 만들어보면 어떨까요 🤩

2020-06-18 22:16 UTC, eastjun commented on js/component/TodoInput.js
> +    const isNotEmpty = event.target.value !== "";
다른 class에서도 재사용할 수 있게 따로 객체로 만들어보면 어떨까요 🤩

2020-06-18 22:16 UTC, eastjun commented on js/component/TodoItem.js
> +    this.isCompleted = this.isSameId(id) ? !this.isCompleted : this.isCompleted;
```javascript
this.isCompleted = this.isSameId(id);
```
위 코드처럼 줄여서 표현할 수 있을 것 같아요!

2020-06-18 22:16 UTC, eastjun commented on js/component/TodoList.js
> +      window.onclick = this.editTodo.bind(this);
`on**`형태의 이벤트 바인딩은 overwrite되어서 원치 않는 에러가 발생할 수 있어요. 특히 다른 개발자와 협업할 때 이벤트를 추가하다가 충돌이 발생할 수 있으니 `addEventListener`를 사용하는게 더 좋을 것 같아요 😄 
[링크 참조](https://stackoverflow.com/questions/6348494/addeventlistener-vs-onclick)

2020-06-18 22:16 UTC, eastjun commented on js/component/TodoList.js
> +    if (isEdit && isEnter) {
모든 if문을 돌아야 하는 이유가 없다면 if문의 연속이 아닌, if else나 switch case로 변경하는걸 추천해요 😄 그렇지 않으면 첫번째 if문에서 종료되는 조건인 경우에도 모든 if문을 돌아야 해요 😢

2020-06-23 12:21 UTC, hwookim commented on js/TodoApp.js
> +    const isAll = target.classList.contains("all");
```javascript
export const FILTER = {
  ALL: "all",
  ACTIVE: "active",
  COMPLETED: "completed",
  of : function (target) {
    return Object.values(this)
      .filter(value => target.classList.contains(value))
      .join();
  }
};
```
이런 식으로 변경해보았습니다!
`TodoApp`에서 하나하나 if문을 순회하지 않고 `this.filter = FILTER.of(target)`을 통해서 `filter`를 제어할 수 있도록 했어요.
다만 object내에서 이런 식으로 혼용하는 게 괜찮은 일인지는 잘 모르겠네요... 😅

2020-06-23 13:29 UTC, hwookim commented on js/TodoApp.js
> +    this.loadItems()
`this.loadItems()`에 대한 `async catch`를 말씀하시는 건가요??
생성자에서는 `async await`를 통한 비동기 작업을 수행할 수 없는 것 같더라구요...
대신 `catch`를 `loadItems()`내부로 옮겼습니다!

2020-11-03 00:13 UTC, closed without merging